### ISSUE TITLE
2 typos in testing Doctrine and releases pages

### ISSUE THREAD

**Issue by alexislefebvre** [symfony-fr/symfony-docs-fr#604]
## A dot is missing at the end of this sentence:

> Heureusement, vous pouvez facilement tester vos requêtes avec une vraie base de données, comme décrit ci-dessous

http://symfony.com/fr/doc/2.3/cookbook/testing/doctrine.html

## Verb agreement
(don't know how to say this in English) *se mettent* doit être accordé avec *l'écosystème*, il doit donc être écrit *l'écosystème Symfony [...] se mette<del>nt</del>*.

> attendre que tout l'écosystème Symfony (bibliothèques tierces, bundles et projets qui utilisent Symfony) se mettent à jour.

http://symfony.com/fr/doc/2.3/contributing/community/releases.html#developpement

Ces changements concernent Symfony 2.3+.

**Comment by mhor** [comment]
@alexislefebvre should be closed
