### ISSUE TITLE
Readme is not up to date

### ISSUE THREAD

**Issue by oktapodia** [symfony-fr/symfony-docs-fr#662]
In the readme, I can see ``` toutes les « pull requests » doivent être basées sur la branche 2.0, et non pas sur la branche master ou la branche 2.1. ``` but this branch is removed

**Comment by oktapodia** [comment]
https://github.com/symfony-fr/symfony-docs-fr/pull/657/files

**Comment by oktapodia** [comment]
https://github.com/symfony-fr/symfony-docs-fr/pull/657

**Comment by mhor** [comment]
@oktapodia should be closed
