### ISSUE TITLE
LInk to PSR0 is not up to date

### ISSUE THREAD

**Issue by oktapodia** [symfony-fr/symfony-docs-fr#663]
I could see on multiple pages the broken links of PSR0

**Comment by oktapodia** [comment]
https://github.com/symfony-fr/symfony-docs-fr/pull/656

**Comment by oktapodia** [comment]
https://github.com/symfony-fr/symfony-docs-fr/pull/656

**Comment by mhor** [comment]
@oktapodia should be closed
