### ISSUE TITLE
Missing 2.1 branch mentioned on homepage

### ISSUE THREAD

**Issue by alexislefebvre** [symfony-fr/symfony-docs-fr#761]
On the homepage it is written / Sur la page d'accueil de ce dépôt il est écrit :

> Ce qui précède concerne le dépôt de la documentation anglaise, et non pas ce dépôt. Si vous trouvez une erreur de traduction, vous êtes prié de faire une Pull Request sur la branche 2.1 et non pas sur la master.

The branch 2.1 doesn't exist / La branche 2.1 n'existe pas : https://github.com/symfony-fr/symfony-docs-fr/branches

**Comment by cmen** [comment]
PR https://github.com/symfony-fr/symfony-docs-fr/pull/637 but this pull request is not merged.

**Comment by alexislefebvre** [comment]
It looks like it had been fixed: https://github.com/symfony-fr/symfony-docs-fr/commit/135ec456df17435f9356d4c3710a32f3a748d6c8#diff-0a369498a5a8db3ac8fa606b544c9810
