### ISSUE TITLE
http://documentation-symfony.fr/ down ?

### ISSUE THREAD

**Issue by olberger** [symfony-fr/symfony-docs-fr#791]
Hi.

Unfortunately, the docs have vanished from the Web : http://downforeveryoneorjustme.com/http://documentation-symfony.fr/

Still, https://web.archive.org/web/20160314025200/http://documentation-symfony.fr/ may be useable :-/

**Comment by gregquat** [comment]
Oui, malheureusement.
Maintenir cette documentation est devenu beaucoup trop difficile avec toutes les améliorations apportées à la documentation anglaise.

De plus, Sensio Labs a décidé de ne plus soutenir les documentations dans les autres langues.
La seule documentaiton officielle et à jour est celle de symfony.com
